package com.pessoas.backend.models;

public enum Escolaridade {
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTA_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    POS_GRADUACAO_INCOMPLETO,
    POS_GRADUACAO_COMPLETO,
    MESTRADO_INCOMPLETO,
    MESTRADO_COMPLETO,
    DOUTORADO_INCOMPLETO,
    DOUTORADO_COMPLETO
}
